---
title: "Tentative Analysis"
author: "Benjamin Osafo Agyare, Connor Dayton, Jaucelyn Canfiled"
date: "4/10/2020"
output:
  pdf_document: 
    fig_width: 7
    fig_height: 6
geometry: right=1cm, left = 1cm, top = 1cm
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, autodep=TRUE, cache.comments=TRUE)
library(tidyverse)
library(mlmRev)
library(lme4)
library(plyr)
library(kableExtra)
library(data.table)
library(readxl)
#library(broom)
library(broom.mixed)
library(bayesplot)
library("coda")
library("rjags")
library("rstanarm")
library(kableExtra)
```

# 1. Data:
```{r, include FALSE}
dat <- readRDS(file = "By_Year_State_updated.rds")
dat$States <- factor(dat$States)

test_row <- seq(14,700,14)
train <- dat[test_row,]
test  <- dat[-test_row,]


kable(head(dat[, 1:7]), "latex", caption = "", booktabs = T) %>%
        kable_styling(latex_options = c("striped", "hold_position"))
kable(head(dat[, c(1,8:13)]), "latex", caption = "", booktabs = T) %>%
        kable_styling(latex_options = c("striped", "hold_position"))
```

\newpage
# 2. Eploratory Data Analysis (EDA):
```{r, warning=FALSE, message=FALSE}
par(mfrow = c(6,9))
ggplot(dat, aes(x = t, y = Y_st)) + geom_point() + facet_wrap(. ~ States)
par(mfrow = c(1,1))
```




# 3. Model formulation:



# 4. Preliminary Analysis:  
```{r, eval = FALSE}
CORES <- parallel::detectCores() - 1
SEED <- 2000

## Classical Model
Model1 <- lmer(formula = Y_st ~  X_t + t + (X_t + t | States), 
           data = test, 
           REML = TRUE)
S <- summary(M3) 
#ranef(Model1)
#fixef(Model1)
#tidy(M3, conf.int = TRUE)

## Bayesian Model
Model2<- stan_lmer(formula = Y_st ~  X_t + t + (X_t + t | States), 
          data = test, cores = CORES, iter = 1e4, control = list(adapt_delta = 0.99),
          prior = normal(location = 0,
                         scale = 5,
                         autoscale = FALSE),
                         prior_intercept = normal(location = 0, 
                         scale = 5, 
                         autoscale = FALSE),
                         seed = SEED)
```












