---
title: "PCA plot for publication"
author: "Alex Knudson"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
library(SWisSFreeNet)

library(patchwork)

library(ggplot2)
library(ggsignif)
library(ggfortify)
library(gtools)
library(RColorBrewer)
```

# Plot function

```{r}
plotmyPCA <- function(dat, title, colorScheme, labelYes=TRUE){
  pca <- prcomp(dat)
  autoplot(pca, colour=colorScheme, label=labelYes, size=4, main=title)
}
```

# Color Schemes

```{r}
farben1 <- brewer.pal(9, 'YlOrRd') # use 4,6,8 for individual conditions
farben2 <- brewer.pal(9, 'YlGnBu') # use 4,6,8 for individual conditions

# differentiate between cell type and treatment
colorScheme1 <- c(rep(farben1[4], 3), rep(farben1[6], 3), rep(farben1[8], 3), 
                  rep(farben2[4], 3), rep(farben2[6], 3), rep(farben2[8], 3))

# differentiate between cell type only
colorScheme2 <- c(rep(farben1[4], 9), 
                  rep(farben2[5], 9))
```

# Plot the PCA

```{r}
p1 <- plotmyPCA(t(na.omit(atoshi_log2quantile)),
                title = "log2-quantile normalized",
                colorScheme = colorScheme1,
                labelYes = TRUE)
p2 <- plotmyPCA(t(na.omit(atoshi_log2quantile)),
                title = "log2-quantile normalized",
                colorScheme = colorScheme2,
                labelYes = FALSE)
p3 <- plotmyPCA(t(na.omit(atoshi_log2quantile)),
                title = "log2-quantile normalized",
                colorScheme = colorScheme1,
                labelYes = FALSE)
```


```{r, fig.width=12, fig.height=4}
p1 + p2 + p3
```

